OUTPUT_DIR = "example"
EMAIL = "myemailname@domain.com"
DATABASE = "my_organism_db.sqlite"
TABLES = ["Assembly","BioSample", "BioProject", "SRA", "Nucleotide"]
SEARCH_TERMS = {"Assembly": "Yersinia pestis[Orgn]",
                "BioProject": "Yersinia pestis[Orgn] AND (bioproject assembly[Filter] OR bioproject sra[Filter])",
                "BioSample": "Yersinia pestis[Orgn] AND (biosample assembly[Filter] OR biosample sra[Filter])",
                "SRA": "Yersinia pestis[Orgn]",
                "Nucleotide": "Yersinia pestis[Orgn] AND WGS_MASTER[KYWD] AND nucleotide assembly[Filter]"}

TABLE_COLUMNS = {
   "Assembly" : [
                {"AssemblyAccession" : "AssemblyAccession"},
                {"BioSampleAccession" : 'BioSampleAccn'},
                {"BioSampleID" : 'BioSampleId'},
                {"GenbankBioprojectAccession" : ["GB_BioProjects","BioprojectAccn"]},
                {"GenbankID" : 'GbUid'},
                {"RefseqBioprojectAccession" : ["RS_BioProjects","BioprojectAccn"]},
                {"RefSeqCategory" : 'RefSeq_category'},
                {"RefSeqID" : 'RsUid'},
                {"WGSAccession" : 'WGS'},
                {"Infraspecies" : ["InfraspeciesList","Biosource","Sub_value"]},
                {"Isolate" : "Isolate"},
                {"Organism" : 'Organism'},
                {"SpeciesTaxonomicID" : 'SpeciesTaxid'},
                {"SpeciesName" : 'SpeciesName'},
                {"TaxonomicID" : 'Taxid'},
                {"AssemblyName" : "AssemblyName"},
                {"AssemblyStatus" : 'AssemblyStatus'},
                {"AssemblyType" : 'AssemblyType'},
                {"AssemblyCoverage" : 'Coverage'},
                {"Chromosomes" : ["Stat", "chromosome_count", "category"]},
                {"ContigCount": ["Stat", "contig_count", "category"]},
                {"ContigN50" : ["Stat", "contig_n50", "category"]},
                {"ContigL50" : ["Stat", "contig_l50", "category"]},
                {"NonChromosomalReplicons" : ["Stat", "non_chromosome_replicon_count", "category"]},
                {"Replicons" : ["Stat", "replicon_count", "category"]},
                {"Scaffolds" : ["Stat", "scaffold_count", "category"]},
                {"ScaffoldN50" : ["Stat", "scaffold_n50", "category"]},
                {"ScaffoldL50" : ["Stat", "scaffold_l50", "category"]},
                {"TotalLength" : ["Stat", "total_length", "category"]},
                {"UngappedLength" : ["Stat", "ungapped_length", "category"]},
                {"SubmitterOrganization" : 'SubmitterOrganization'},
                {"SubmissionDate" : 'SubmissionDate'},
                {"ReleaseDate" : 'SeqReleaseDate'},
                {"FTPAssemblyReport" : 'FtpPath_Assembly_rpt'},
                {"FTPGenbank" : 'FtpPath_GenBank'},
                {"FTPRefSeq" : 'FtpPath_RefSeq'},
                {"FTPStatsReport" : 'FtpPath_Stats_rpt'}
                ],
  "BioSample" : [
                {"Accession": "Accession"},
                {"BioProject": ["Link","label"]},
                {"SRAAccession": ["Id","SRA","db"]},
                {"BioSampleTitle": "Title"},
                {"SampleName": ["Id","Sample name","db_label"]},
                {"SampleType": ["Attribute","sample_type","attribute_name"]},
                {"Package": "Package"},
                {"Infraspecies": "Infraspecies"},
                {"Organism": "OrganismName"},
                {"OrganismAlt": ["Organism","taxonomy_name"]},
                {"SubSpecies": ["Attribute","sub_species","attribute_name"]},
                {"Strain": ["Attribute","strain","attribute_name"]},
                {"TaxonomyID": "Taxonomy"},
                {"Biovar": ["Attribute","biovar","attribute_name"]},
                {"CollectionDate": ["Attribute","collection_date","attribute_name"]},
                {"GeographicLocation": ["Attribute","geo_loc_name","attribute_name"]},
                {"Host": ["Attribute","host","attribute_name"]},
                {"HostDisease" : ["Attribute", "host_disease", "attribute_name"]},
                {"IsolateNameAlias": ["Attribute","isolate-name-alias","attribute_name"]},
                {"IsolationSource": ["Attribute","isolation_source","attribute_name"]},
                {"Lat" : ["Attribute", "latitude", "attribute_name"]},
                {"LatLon" : ["Attribute", "lat_lon", "attribute_name"]},
                {"Lon" : ["Attribute", "longitude", "attribute_name"]},
                {"Date": "Date"},
                {"ModificationDate": "ModificationDate"},
                {"PublicationDate": "PublicationDate"},
                {"Organization": "Organization"}
                ],
 "BioProject" : [
                {"BioProjectAccession" : "Project_Acc"},
                {"DataType" : "Project_Data_Type"},
                {"Description" : "Project_Description"},
                {"MethodType" : "Project_MethodType"},
                {"Name" : "Project_Name"},
                {"TargetCapture" : "Project_Target_Capture"},
                {"TargetMaterial" : "Project_Target_Material"},
                {"TargetScope" : "Project_Target_Scope"},
                {"Title" : "Project_Title"},
                {"Type" : "Project_Type"},
                {"OrganismLabel" : "Organism_Label"},
                {"OrganismStrain" : "Organism_Strain"},
                {"Supergroup" : "Supergroup"},
                {"TaxonomicID" : "TaxId"},
                {"RegistrationDate" : "Registration_Date"},
                {"RelevanceMedical" : "Relevance_Medical"},
                {"SequencingStatus" : "Sequencing_Status"},
                {"SubmitterOrganization" : "Submitter_Organization"}
                ],
 "Nucleotide" : [
                {"Accession" : 'GBSeq_primary-accession'},
                {"AccessionVersion" : 'GBSeq_accession-version'},
                {"BioSample": "NucleotideBioSample"},
                {"BioProject" : "GBSeq_project"},
                {"FirstAccession" : ['GBAltSeqData_items', 'GBSeq_alt-seq', 'GBAltSeqItem_first-accn']},
                {"LastAccession" : ['GBAltSeqData_items', 'GBSeq_alt-seq', 'GBAltSeqItem_last-accn']},
                {"Organism" : 'GBSeq_organism'},
                {"Taxonomy" : "GBSeq_taxonomy"},
                {"Definition" : "GBSeq_definition"},
                {"Division" : "GBSeq_division"},
                {"Journal": ['GBSeq_references', 'GBReference_journal']},
                {"Length" : 'GBSeq_length'},
                {"MoleculeType" : "GBSeq_moltype"},
                {"ReferenceTitle": ['GBSeq_references', u'GBReference_title']},
                {"SeqDataName" : ['GBSeq_alt-seq', 'GBAltSeqData_name']},
                {"Source" : 'GBSeq_source'},
                {"Strandedness" : "GBSeq_strandedness"},
                {"Topology" : "GBSeq_topology"},
                {"CreateDate" : "GBSeq_create-date"},
                {"UpdateDate" : "GBSeq_update-date"},
                {"Comment" : "GBSeq_comment"},
                {'AnnotationDate': 'Annotation Date'},
                {'AnnotationMethod': 'Annotation Method'},
                {'AnnotationPipeline': 'Annotation Pipeline'},
                {'AnnotationProvider': 'Annotation Provider'},
                {'AnnotationSoftwarerevision': 'Annotation Software revision'},
                {'AssemblyDate': 'Assembly Date'},
                {'AssemblyMethod': 'Assembly Method'},
                {'AssemblyName': 'Assembly Name'},
                {'CDS': 'CDS (total)'},
                {'CDSCoding': 'CDS (coding)'},
                {'CRISPRArrays': 'CRISPR Arrays'},
                {'ExpectedFinalVersion': 'Expected Final Version'},
                {'FeaturesAnnotated': 'Features Annotated'},
                {'Genes': 'Genes (total)'},
                {'GenesCoding': 'Genes (coding)'},
                {'GenesRNA': 'Genes (RNA)'},
                {'GenomeCoverage': 'Genome Coverage'},
                {'GenomeRepresentation': 'Genome Representation'},
                {'ncRNAs': 'ncRNAs'},
                {'PseudoGenes': 'Pseudo Genes (total)'},
                {'PseudoGenesAmbResidues': 'Pseudo Genes (ambiguous residues)'},
                {'PseudoGenesFrameshifted': 'Pseudo Genes (frameshifted)'},
                {'PseudoGenesIncomplete': 'Pseudo Genes (incomplete)'},
                {'PseudoGenesInternalStop': 'Pseudo Genes (internal stop)'},
                {'PseudoGenesMultipleProblems': 'Pseudo Genes (multiple problems)'},
                {'rRNAs': 'rRNAs'},
                {'rRNAsComplete': 'complete rRNAs'},
                {'rRNAsPartial': 'partial rRNAs'},
                {'SequencingTechnology': 'Sequencing Technology'},
                {'tRNAs': 'tRNAs'}
                ],
        "SRA" : [
                {"BioProjectAccession" : "Bioproject"},
                {"BioSampleAccession" : "Biosample"},
                {"ExperimentAccession" : ["Experiment", "acc"]},
                {"RunAccession" : ["Run", "acc"]},
                {"SampleAccession" : ["Sample", "acc"]},
                {"ExperimentName" : ["Experiment", "name"]},
                {"ExperimentStatus" : ["Experiment", "status"]},
                {"ExperimentVersion" : ["Experiment", "ver"]},
                {"IsPublic" : ["Run", "is_public"]},
                {"SampleName" : ["Sample", "name"]},
                {"StaticDataAvailable" : ["Run", "static_data_available"]},
                {"StudyAcc" : ["Study", "acc"]},
                {"StudName" : ["Study", "name"]},
                {"Title" : "Title"},
                {"OrganismName" : ["Organism", "CommonName"]},
                {"OrganismTaxID" : ["Organism", "taxid"]},
                {"ClusterName" : ["Statistics", "cluster_name"]},
                {"InstrumentModel" : ["Platform", "instrument_model"]},
                {"LibraryName" : "LIBRARY_NAME"},
                {"LibraryLayout" : "LIBRARY_LAYOUT"},
                {"LibrarySelection" : "LIBRARY_SELECTION"},
                {"LibrarySource" : "LIBRARY_SOURCE"},
                {"LibraryStrategy" : "LIBRARY_STRATEGY"},
                {"Platform" : "Platform"},
                {"TotalBases" : ["Statistics", "total_bases"]},
                {"TotalSize" : ["Statistics", "total_size"]},
                {"TotalSpots" : ["Statistics", "total_spots"]},
                {"TotalRuns" : ["Statistics", "total_runs"]},
                {"CreateDate" : "CreateDate"},
                {"UpdateDate" : "UpdateDate"},
                {"CenterName" : ["Submitter", "center_name"]},
                {"ContactName" : ["Submitter", "contact_name"]},
                {"LabName" : ["Submitter", "lab_name"]},
                {"SubmitterAccession" : ["Submitter", "acc"]}
                ]
                }
