# Markdown_lint configuration file
default: true,
line-length: false
no-trailing-punctuation: false
no-duplicate-header:
  siblings_only: true
no-trailing-spaces:
  br_spaces: 2
no-inline-html:
  allowed_elements:
    - img
