OUTPUT_DIR = "../NCBImeta_ouput/"
EMAIL = "ktmeaton@gmail.com"
DATABASE = "plasmodium_falciparum_db.sqlite"
TABLES = ["Assembly","BioSample", "BioProject", "Nucleotide"]
SEARCH_TERMS = {"Assembly": "Plasmodium falciparum[Orgn]",
                "BioProject": "Plasmodium falciparum[Orgn] AND (bioproject assembly[Filter])",
                "BioSample": "Plasmodium falciparum[Orgn] AND (biosample assembly[Filter])",
                "Nucleotide": "Plasmodium falciparum[Orgn] AND WGS_MASTER[KYWD] AND nucleotide assembly[Filter]"}

TABLE_COLUMNS = {
                "Assembly": [
                            {"AssemblyAccession" : "AssemblyAccession"},
                            {"AssemblyName" : "AssemblyName"},
                            {"Organism" : 'Organism'},
                            {"AssemblyStatus" : 'AssemblyStatus'},
                            {"AssemblyType" : 'AssemblyType'},
                            {"SubmitterOrganization" : 'SubmitterOrganization'},
                            {"TaxonomicID" : 'Taxid'},
                            {"SpeciesTaxonomicID" : 'SpeciesTaxid'},
                            {"SpeciesName" : 'SpeciesName'},
                            {"BioSampleAccession" : 'BioSampleAccn'},
                            {"BioSampleID" : 'BioSampleId'},
                            {"AssemblyCoverage" : 'Coverage'},
                            {"SubmissionDate" : 'SubmissionDate'},
                            {"ReleaseDate" : 'SeqReleaseDate'},
                            {"WGSAccession" : 'WGS'},
                            {"Isolate" : "Isolate"},
                            {"Chromosomes" : ["Stat", "chromosome_count", "category"]},
                            {"Replicons" : ["Stat", "replicon_count", "category"]},
                            {"NonChromosomalReplicons" : ["Stat", "non_chromosome_replicon_count", "category"]},
                            {"ContigCount": ["Stat", "contig_count", "category"]},
                            {"ContigN50" : ["Stat", "contig_n50", "category"]},
                            {"ContigL50" : ["Stat", "contig_l50", "category"]},
                            {"Scaffolds" : ["Stat", "scaffold_count", "category"]},
                            {"ScaffoldN50" : ["Stat", "scaffold_n50", "category"]},
                            {"ScaffoldL50" : ["Stat", "scaffold_l50", "category"]},
                            {"TotalLength" : ["Stat", "total_length", "category"]},
                            {"UngappedLength" : ["Stat", "ungapped_length", "category"]},
                            {"RefSeqID" : 'RsUid'},
                            {"GenbankID" : 'GbUid'},
                            {"RefSeqCategory" : 'RefSeq_category'},
                            {"FTPGenbank" : 'FtpPath_GenBank'},
                            {"FTPRefSeq" : 'FtpPath_RefSeq'},
                            {"FTPAssemblyReport" : 'FtpPath_Assembly_rpt'},
                            {"FTPStatsReport" : 'FtpPath_Stats_rpt'},
                            {"GenbankBioprojectAccession" : ["GB_BioProjects","BioprojectAccn"]},
                            {"RefseqBioprojectAccession" : ["RS_BioProjects","BioprojectAccn"]},
                            {"Infraspecies" : ["InfraspeciesList","Biosource","Sub_value"]}
                              ],
                "BioSample": [
                             {"Accession": "Accession"},
                             {"BioSampleTitle": "Title"},
                             {"TaxonomyID": "Taxonomy"},
                             {"SRAAccession": ["Id","SRA","db"]},
                             {"SampleName": ["Id","Sample name","db_label"]},
                             {"Infraspecies": "Infraspecies"},
                             {"ModificationDate": "ModificationDate"},
                             {"PublicationDate": "PublicationDate"},
                             {"Package": "Package"},
                             {"Date": "Date"},
                             {"Organization": "Organization"},
                             {"Organism": "OrganismName"},
                             {"OrganismAlt": ["Organism","taxonomy_name"]},
                             {"Strain": ["Attribute","strain","attribute_name"]},
                             {"CollectionDate": ["Attribute","collection_date","attribute_name"]},
                             {"GeographicLocation": ["Attribute","geo_loc_name","attribute_name"]},
                             {"SampleType": ["Attribute","sample_type","attribute_name"]},
                             {"Host": ["Attribute","host","attribute_name"]},
                             {"IsolationSource": ["Attribute","isolation_source","attribute_name"]},
                             {"Biovar": ["Attribute","biovar","attribute_name"]},
                             {"SubSpecies": ["Attribute","sub_species","attribute_name"]},
                             {"IsolateNameAlias": ["Attribute","isolate-name-alias","attribute_name"]},
                             {"LatLon" : ["Attribute", "lat_lon", "attribute_name"]},
                             {"Lat" : ["Attribute", "latitude", "attribute_name"]},
                             {"Lon" : ["Attribute", "longitude", "attribute_name"]},
                             {"HostDisease" : ["Attribute", "host_disease", "attribute_name"]},
                             {"BioProject": ["Link","label"]}
                              ],
                "BioProject": [
                              {"BioProjectAccession" : "Project_Acc"},
                              {"TargetScope" : "Project_Target_Scope"},
                              {"TargetCapture" : "Project_Target_Capture"},
                              {"TargetMaterial" : "Project_Target_Material"},
                              {"Description" : "Project_Description"},
                              {"MethodType" : "Project_MethodType"},
                              {"Name" : "Project_Name"},
                              {"Title" : "Project_Title"},
                              {"OrganismLabel" : "Organism_Label"},
                              {"OrganismStrain" : "Organism_Strain"},
                              {"Type" : "Project_Type"},
                              {"DataType" : "Project_Data_Type"},
                              {"Supergroup" : "Supergroup"},
                              {"TaxonomicID" : "TaxId"},
                              {"RegistrationDate" : "Registration_Date"},
                              {"SequencingStatus" : "Sequencing_Status"},
                              {"RelevanceMedical" : "Relevance_Medical"},
                              {"SubmitterOrganization" : "Submitter_Organization"}
                              ],
                       "SRA": [
                              {"CreateDate" : "CreateDate"},
                              {"UpdateDate" : "UpdateDate"},
                              {"Title" : "Title"},
                              {"Platform" : "Platform"},
                              {"LibraryName" : "LIBRARY_NAME"},
                              {"LibraryStrategy" : "LIBRARY_STRATEGY"},
                              {"LibrarySource" : "LIBRARY_SOURCE"},
                              {"LibrarySelection" : "LIBRARY_SELECTION"},
                              {"LibraryLayout" : "LIBRARY_LAYOUT"},
                              {"BioProjectAccession" : "Bioproject"},
                              {"BioSampleAccession" : "Biosample"},
                              {"ClusterName" : ["Statistics", "cluster_name"]},
                              {"TotalBases" : ["Statistics", "total_bases"]},
                              {"TotalSpots" : ["Statistics", "total_spots"]},
                              {"TotalRuns" : ["Statistics", "total_runs"]},
                              {"TotalSize" : ["Statistics", "total_size"]},
                              {"StaticDataAvailable" : ["Run", "static_data_available"]},
                              {"IsPublic" : ["Run", "is_public"]},
                              {"InstrumentModel" : ["Platform", "instrument_model"]},
                              {"SubmitterAccession" : ["Submitter", "acc"]},
                              {"CenterName" : ["Submitter", "center_name"]},
                              {"ContactName" : ["Submitter", "contact_name"]},
                              {"LabName" : ["Submitter", "lab_name"]},
                              {"ExperimentAccession" : ["Experiment", "acc"]},
                              {"ExperimentName" : ["Experiment", "name"]},
                              {"ExperimentStatus" : ["Experiment", "status"]},
                              {"ExperimentVersion" : ["Experiment", "ver"]},
                              {"StudyAcc" : ["Study", "acc"]},
                              {"StudName" : ["Study", "name"]},
                              {"OrganismName" : ["Organism", "CommonName"]},
                              {"OrganismTaxID" : ["Organism", "taxid"]},
                              {"SampleAccession" : ["Sample", "acc"]},
                              {"SampleName" : ["Sample", "name"]},
                              {"RunAccession" : ["Run", "acc"]}
                              ],
                "Nucleotide": [
                            {"BioSample": "NucleotideBioSample"},
                            {"MoleculeType" : "GBSeq_moltype"},
                            {"Comment" : "GBSeq_comment"},
                            {"Strandedness" : "GBSeq_strandedness"},
                            {"Definition" : "GBSeq_definition"},
                            {"Organism" : 'GBSeq_organism'},
                            {"Source" : 'GBSeq_source'},
                            {"Accession" : 'GBSeq_primary-accession'},
                            {"AccessionVersion" : 'GBSeq_accession-version'},
                            {"Length" : 'GBSeq_length'},
                            {"CreateDate" : "GBSeq_create-date"},
                            {"UpdateDate" : "GBSeq_update-date"},
                            {"Division" : "GBSeq_division"},
                            {"Topology" : "GBSeq_topology"},
                            {"Taxonomy" : "GBSeq_taxonomy"},
                            {"BioProject" : "GBSeq_project"},
                            {'AssemblyDate': 'Assembly Date'},
                            {'AssemblyMethod': 'Assembly Method'},
                            {'AssemblyName': 'Assembly Name'},
                            {'GenomeRepresentation': 'Genome Representation'},
                            {'ExpectedFinalVersion': 'Expected Final Version'},
                            {'GenomeCoverage': 'Genome Coverage'},
                            {'SequencingTechnology': 'Sequencing Technology'},
                            {'AnnotationProvider': 'Annotation Provider'},
                            {'AnnotationDate': 'Annotation Date'},
                            {'AnnotationPipeline': 'Annotation Pipeline'},
                            {'AnnotationMethod': 'Annotation Method'},
                            {'AnnotationSoftwarerevision': 'Annotation Software revision'},
                            {'FeaturesAnnotated': 'Features Annotated'},
                            {'Genes': 'Genes (total)'},
                            {'CDS': 'CDS (total)'},
                            {'GenesCoding': 'Genes (coding)'},
                            {'CDSCoding': 'CDS (coding)'},
                            {'GenesRNA': 'Genes (RNA)'},
                            {'rRNAs': 'rRNAs'},
                            {'rRNAsComplete': 'complete rRNAs'},
                            {'rRNAsPartial': 'partial rRNAs'},
                            {'tRNAs': 'tRNAs'},
                            {'ncRNAs': 'ncRNAs'},
                            {'PseudoGenes': 'Pseudo Genes (total)'},
                            {'PseudoGenesAmbResidues': 'Pseudo Genes (ambiguous residues)'},
                            {'PseudoGenesFrameshifted': 'Pseudo Genes (frameshifted)'},
                            {'PseudoGenesIncomplete': 'Pseudo Genes (incomplete)'},
                            {'PseudoGenesInternalStop': 'Pseudo Genes (internal stop)'},
                            {'PseudoGenesMultipleProblems': 'Pseudo Genes (multiple problems)'},
                            {'CRISPRArrays': 'CRISPR Arrays'},
                            {"Journal": ['GBSeq_references', 'GBReference_journal']},
                            {"ReferenceTitle": ['GBSeq_references', u'GBReference_title']},
                            {"FirstAccession" : ['GBAltSeqData_items', 'GBSeq_alt-seq', 'GBAltSeqItem_first-accn']},
                            {"LastAccession" : ['GBAltSeqData_items', 'GBSeq_alt-seq', 'GBAltSeqItem_last-accn']},
                            {"SeqDataName" : ['GBSeq_alt-seq', 'GBAltSeqData_name']}
                            ]   }
