#------------------------------------------------------------------------------#
name: Build
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - '.github/workflows/build.yaml*'
      - 'ncbimeta/*'
      - 'test/*'
      - 'requirements.txt'
      - 'setup.py'
      - 'setup.cfg'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Build Binary
  build_binary:
    name: Build Binary
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Python Setup ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install .[dev]
          NCBImeta --version
          pyinstaller --version

      - name: Build Binary
        run: |
          pyinstaller ncbimeta/NCBImeta
          dist/NCBImeta/NCBImeta --version
          tar -czvf ncbimeta-${{ matrix.os }}.tar.gz dist/NCBImeta/NCBImeta

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: ncbimeta-${{ matrix.os }}
          path: ncbimeta-${{ matrix.os }}.tar.gz
