#------------------------------------------------------------------------------#
name: Install
#------------------------------------------------------------------------------#
# Workflow conditions
on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - '.github/workflows/install.yaml*'
      - 'ncbimeta/*'
      - 'test/*'
      - 'requirements.txt'
      - 'setup.py'
      - 'setup.cfg'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
#------------------------------------------------------------------------------#
jobs:
  #----------------------------------------------------------------------------#
  # Source Install
  source_install:
    name: Source Install
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Python Setup ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install From Source
        run: |
          pip install .
          NCBImeta --version
  #----------------------------------------------------------------------------#
  # PyPI Install
  pypi_install:
    name: PyPI Install
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Python Setup ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Remove the .py after v0.8.0
      - name: Install from PyPI
        run: |
          pip install ncbimeta
          NCBImeta --version
  #----------------------------------------------------------------------------#
  # Conda Install
  conda_install:
    name: Conda Install
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Conda
        uses:  conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge

      - name: Install From Conda
        shell: bash -l {0}
        run: |
          mamba create -c conda-forge -c bioconda -n ncbimeta ncbimeta
          conda activate ncbimeta
          NCBImeta --version

      - name: lxml Hotfix
        shell: bash -l {0}
        run: |
          conda activate ncbimeta
          pip uninstall --yes lxml
          pip install lxml
